In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('rfm_segments.csv')

In [3]:
df.head()

   Customer ID  Recency  Frequency  Monetary  Cluster  Segment
0        12346      326         12  77556.46        1  Regular
1        12347        2          8   5633.32        1  Regular
2        12348       75          5   2019.40        1  Regular
3        12349       19          4   4428.69        1  Regular
4        12350      310          1    334.40        0  At Risk

In [4]:
df['AvgOrderValue'] = df['Monetary'] / df['Frequency']

In [5]:
df.head()

   Customer ID  Recency  Frequency  Monetary  Cluster  Segment  AvgOrderValue
0        12346      326         12  77556.46        1  Regular    6463.038333
1        12347        2          8   5633.32        1  Regular     704.165000
2        12348       75          5   2019.40        1  Regular     403.880000
3        12349       19          4   4428.69        1  Regular    1107.172500
4        12350      310          1    334.40        0  At Risk     334.400000

In [6]:
df.to_csv('rfm_features_full.csv', index=False)